import { NextResponse } from "next/server";

export async function POST(req: Request) {
  try {
    const { prompt, language } = await req.json();

    if (!prompt) {
      return NextResponse.json({ error: "Prompt is required" }, { status: 400 });
    }

    const code = `// Amosclaud AI Code Generator
// Language: ${language || "JavaScript"}
// Request: ${prompt}

export default function GeneratedFeature() {
  return (
    <main style={{ padding: 24 }}>
      <h1>Generated by Amosclaud AI</h1>
      <p>${prompt}</p>
    </main>
  );
}
`;

    return NextResponse.json({
      success: true,
      code,
    });
  } catch (error) {
    return NextResponse.json(
      { error: "AI code generation failed" },
      { status: 500 }
    );
  }
}
