import { NextResponse } from "next/server";

export async function POST(req: Request) {
  try {
    const { prompt, language } = await req.json();

    if (!prompt) {
      return NextResponse.json(
        { error: "Prompt is required" },
        { status: 400 }
      );
    }

    const generatedCode = `
// Generated by Amosclaud AI Test
// Language: ${language || "TypeScript"}

export default function Example() {
  return (
    <div>
      <h1>${prompt}</h1>
      <p>This proves the ai-code API route is working.</p>
    </div>
  );
}
`;

    return NextResponse.json({
      success: true,
      code: generatedCode,
    });
  } catch {
    return NextResponse.json(
      { success: false, error: "Failed to generate code" },
      { status: 500 }
    );
  }
}
