import { NextResponse } from "next/server";

export async function POST(req: Request) {
  try {
    const { prompt, language } = await req.json();

    if (!prompt) {
      return NextResponse.json(
        {
          success: false,
          error: "Prompt is required"
        },
        { status: 400 }
      );
    }

    const generatedCode = `
// Generated by Amosclaud AI Test

// Language: ${language || "TypeScript"}

export default function Example() {
  return (
    <div style={{ padding: "20px" }}>
      <h1>${prompt}</h1>
      <p>AI Code Generator API is working.</p>
    </div>
  );
}
`;

    return NextResponse.json({
      success: true,
      code: generatedCode,
      timestamp: new Date().toISOString()
    });
  } catch (error) {
    console.error(error);

    return NextResponse.json(
      {
        success: false,
        error: "Failed to generate code"
      },
      { status: 500 }
    );
  }
}
